
name: POC maven - sonarqube - nexus

on:
  push:
    branches:
      - master

jobs:
  runs-on: [ ubuntu-20.04 ]

  maven_tasks:
    name: Maven Taskss
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Maven - clean workspace
      run: mvn clean
    - name: Maven - Build
      run: mvn install
    - name: Maven - Test
      run: mvn test

  sonarqube_scanner:
    name: Sonarqube scan and report generate
    steps:
    - name: Setup Sonarqube scanner
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonar-scanner
      #env:
      #  to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
           -Dsonar.organization=com.mycompany.app
           -Dsonar.projectKey=com.eldisol:jacoboot
           -Dsonar.projectName=jacoboot
           -Dsonar.projectVersion=0.1
           -Dsonar.sources=.
           -Dsonar.sourceEncoding=UTF-8
