
name: POC maven - sonarqube - nexus

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  qa_and_vs_check:
    runs-on: [ ubuntu-20.04 ]
    name: Test, vulnerability checks and report coverage
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Maven - run tests
      run: mvn verify
    - name: Maven - vulnerability check
      run: mvn org.owasp:dependency-check-maven:check
    #name: Continuos Integration - generate report coverate
    - name: Maven - generate report coverage
      run: mvn sonar:sonar
           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
           -Dsonar.dependencyCheck.htmlReportPath=./target/dependency-check-report.html
           #-Dsonar.projectKey=com.eldisol:jacoboot
           #-Dsonar.projectName=jacoboot
           #-Dsonar.projectVersion=0.0.1-SNAPSHOT
           #-Dsonar.sources=.
           #-Dsonar.sourceEncoding=UTF-8

  build_and_deply:
    runs-on: [ ubuntu-20.04 ]
    name: Build and deploy
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Maven - building
      run: mvn package
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: ${{ secrets.NEXUS3_HOST }}
        username: ${{ secrets.NEXUS3_USER }}
        password: ${{ secrets.NEXUS3_PASSWORD }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=com.eldisol artifactId=jacoboot version=0.0.1
        assets: extension=jar
        filename: ./target/jacoboot-0.0.1.jar
