
name: POC maven - sonarqube - nexus

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ ubuntu-20.04 ]
    name: Continuos Integration - build, test and scan
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Maven - Clean and verify project
      run: mvn clean verify
    - name: Maven - Build
      run: mvn install
    - name: Maven - Test
      run: mvn test
    #name: Continuos Integration - generate report coverate
    #steps:
    - name: Setup Sonarqube scanner
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonar-scanner
      run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
           -Dsonar.projectKey=com.eldisol:jacoboot
           -Dsonar.projectName=jacoboot
           -Dsonar.projectVersion=0.1
           -Dsonar.sources=.
           -Dsonar.sourceEncoding=UTF-8

    #- name: Nexus Repo Publish
    #  uses: sonatype-nexus-community/nexus-repo-github-action@master
    #  with:
    #    serverUrl: http://163c6cdd.ngrok.io
    #    username: admin
    #    password: ${{ secrets.password }}
    #    format: maven2
    #    repository: maven-releases
    #    coordinates: groupId=com.example artifactId=app version=1.0.0
    #    assets: extension=jar
    #    filename: ./target/app-1.0.0.jar
