
name: POC deploy and promotion production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: [ ubuntu-20.04 ]
    name: Deploy RC in production
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Data mining - get pom informations
      run: |
        echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        echo "POM_GROUPID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
        echo "POM_ARTIFACTID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
        echo "POM_NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)" >> $GITHUB_ENV
        echo "POM_DESCRIPTION=$(mvn help:evaluate -Dexpression=project.description -q -DforceStdout)" >> $GITHUB_ENV

      # To Do: with Ansible
    - name: Get application from nexus
      run: curl -v -O ${{ secrets.NEXUS3_HOST }}/repository/maven-releases/$POM_GROUPID/$POM_ARTIFACTID/$POM_VERSION/$POM_NAME-$POM_VERSION.jar

      # To Do: with Ansible
    - name: Run application - demo
      run: echo "java -jar ./$POM_NAME-$POM_VERSION.jar"
